name: "Install cicd-utilities"
description: "Install latest release of cicd-utilities from GitHub"
runs:
  using: "composite"
  steps:
    - name: Fetch latest release binary
      shell: bash
      run: |
        curl -s https://api.github.com/repos/davidjspooner/cicd-utilities/releases/latest \
        | grep "browser_download_url" \
        | cut -d '"' -f 4 \
        | xargs curl -L -o cicd-utilities
        chmod +x cicd-utilities
        mv cicd-utilities /usr/local/bin/cicd-utilities
