name: "Update PR Meta"
description: "Updates pull request title and description based on commit messages"

inputs:
  pr-number:
    description: "The pull request number to update"
    required: true
  github-token:
    description: "GitHub token for authentication"
    required: true
  dry-run:
    description: "Perform a dry run without updating the PR"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Run update-github-pr-meta
      shell: bash
      run: |
        pwd
        go run ../../../cmd/cicd update-github-pr-meta \
          --pr ${{ inputs.pr-number }} \
          --dry-run ${{ inputs.dry-run }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
