name: "Set Git Tag"
description: "A custom action to run the set-git-tag tool"

inputs:
  prefix:
    description: "Prefix for the new tag"
    required: false
    default: ""
  suffix:
    description: "Suffix for the new tag"
    required: false
    default: ""
  dry-run:
    description: "Perform a dry run without updating the tag"
    required: false
    default: "false"
  remote:
    description: "Remote to push the tag to"
    required: false
    default: "origin"

runs:
  using: "composite"
  steps:
    - name: Run bump-git-tag
      shell: bash
      run: |
        pwd
        go run ../../../cmd/cicd bump-git-tag \
          --prefix ${{ inputs.prefix }} \
          --suffix ${{ inputs.suffix }} \
          --remote ${{ inputs.remote }} \
          --dry-run ${{ inputs.dry-run }}
