name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Build binary
        run: |
          echo "Building for ${{ matrix.arch }}"
          pwd
          ls -la
          rm -rf dist
          mkdir -p dist/{{ matrix.arch }}
          GOOS=linux GOARCH=${{ matrix.arch }} CGO_ENABLED=0 go build -ldflags="-s -w" -o ./dist/cicd-utilities-${{ matrix.arch }}/cicd-utilities ./cmd/cicd-utilitiies

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: cicd-utilities-${{ matrix.arch }}
          path: dist/cicd-utilities-${{ matrix.arch }}/
          retention-days: 1

      - name: List structure
        run: |
          echo "Listing structure"
          pwd
          ls -laR dist
  
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Make dist directory
        run: mkdir -p dist
      - name: Download artifact
        uses: actions/download-artifact@v4.3.0
        with:
          path: dist/
          merge-multiple: true

      - name: List structure
        run: |
          echo "Listing structure"
          pwd
          ls -laR dist

