name: Build and Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Build binary
        run: |
          echo "Building for ${{ matrix.arch }}"
          rm -rf dist
          mkdir -p dist/{{ matrix.arch }}
          GOOS=linux GOARCH=${{ matrix.arch }} CGO_ENABLED=0 go build -ldflags="-s -w" -o dist/${{ matrix.arch }}/cicd-utilities cmd/cicd

      - name: Tar binary
        run: |
          tar -czf dist/cicd-utilities-${{ matrix.arch }}.tar.gz -C dist/${{ matrix.arch }} *
