name: Build and Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Build binary
        run: |
          echo "Building for ${{ matrix.arch }}"
          pwd
          ls -la
          rm -rf dist
          mkdir -p dist/{{ matrix.arch }}
          GOOS=linux GOARCH=${{ matrix.arch }} CGO_ENABLED=0 go build -ldflags="-s -w" -o ./dist/${{ matrix.arch }}/cicd-utilities ./cmd/cicd-utilitiies

      - name: Create tarball
        run: |
          echo "Creating tarball for ${{ matrix.arch }}"
          tar -czf cicd-utilities-${{ matrix.arch }}.tar.gz -C ./dist/${{ matrix.arch }} cicd-utilities
          ls -la dist/${{ matrix.arch }}

      - name: Upload tarball
        uses: actions/upload-artifact@v3
        with:
          name: cicd-utilities-${{ matrix.arch }}.tar.gz